cache:
  directories:
  - $HOME/.m2
dist: trusty
language: java
jdk:
- openjdk8
addons:
  sonarcloud:
    organization: "younessfathi"
    token:
      secure: "3277a5d8b47e87c2a9480090832ff61697ab1880"
script:
- mvn -B clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar  -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=${PROJECT_KEY} -Dsonar.organization=${ORGANIZATION} -Dsonar.login=${SONAR_LOGIN};